#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNet.Identity;

namespace uLearn.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Database.DataContexts;
    using Database.Models;
    using HtmlHelper = System.Web.Mvc.HtmlHelper;
    using Ulearn.Common;
    using Ulearn.Common.Extensions;
    using Ulearn.Core;
    using Ulearn.Core.Courses;
    using Ulearn.Core.Courses.Slides;
    using Ulearn.Core.Courses.Slides.Exercises;
    using Ulearn.Core.Courses.Slides.Quizzes;
    using Ulearn.Core.Extensions;
    using uLearn.Web;
    using uLearn.Web.Extensions;
    using uLearn.Web.Models;
    using uLearn.Web.Views.Shared;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class Notifications : System.Web.WebPages.HelperPage
    {
 

	private static string GetSlideUrl(UrlHelper Url, Course course, Slide slide)
	{
		return Url.RouteUrl("Course.SlideById", new { courseId = course.Id, slideId = slide.Url });
	}

	private static IHtmlString CollapseIfNeed(bool collapse, HtmlHelper Html, string text, int truncateMaxLength, bool renderSimpleMarkdown = false)
	{
		var encodedText = Html.EncodeMultiLineText(text);
		if (renderSimpleMarkdown)
			encodedText = encodedText.RenderSimpleMarkdown();
		if (collapse)
			encodedText = encodedText.TruncateHtmlWithEllipsis(truncateMaxLength);
		return Html.Raw(collapse ? encodedText : Html.HighlightLink(encodedText));
	}


#line default
#line hidden
public static System.Web.WebPages.HelperResult SlideLink(UrlHelper Url, Course course, Slide slide)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 1272), Tuple.Create("\"", 1311)
, Tuple.Create(Tuple.Create("", 1279), Tuple.Create<System.Object, System.Int32>(GetSlideUrl(Url, course, slide)
, 1279), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                 WriteTo(__razor_helper_writer, slide.Title.TruncateWithEllipsis(40));

WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult UserName(ApplicationUser user)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__user\"");

WriteLiteralTo(__razor_helper_writer, ">");

                      WriteTo(__razor_helper_writer, user.VisibleName);

WriteLiteralTo(__razor_helper_writer, "</span>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(SystemMessageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__system-message-notification without-link media\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"\"");

WriteLiteralTo(__razor_helper_writer, ">");

WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Text, 100));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 1893), Tuple.Create("\"", 1942)
, Tuple.Create(Tuple.Create("", 1901), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 1901), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(InstructorMessageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__instructor-message-notification without-link media\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, ":</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"\"");

WriteLiteralTo(__razor_helper_writer, ">");

WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Text, 100));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 2582), Tuple.Create("\"", 2631)
, Tuple.Create(Tuple.Create("", 2590), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 2590), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(NewCommentNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideByIdNotSafe(notification.Comment.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__new-comment-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                            WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "#comment-");

                                                                                     WriteTo(__razor_helper_writer, notification.Comment.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__subheader\"");

WriteLiteralTo(__razor_helper_writer, ">к&nbsp;слайду ");

                                                     WriteTo(__razor_helper_writer, SlideLink(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "</span>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 3396), Tuple.Create("\"", 3456)
, Tuple.Create(Tuple.Create("", 3404), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 3404), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 3658), Tuple.Create("\"", 3707)
, Tuple.Create(Tuple.Create("", 3666), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 3666), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(NewCommentFromYourGroupStudentNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideByIdNotSafe(notification.Comment.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__new-comment-from-your-group-student-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                                    WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "#comment-");

                                                                                                             WriteTo(__razor_helper_writer, notification.Comment.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__subheader\"");

WriteLiteralTo(__razor_helper_writer, ">к&nbsp;слайду ");

                                                     WriteTo(__razor_helper_writer, SlideLink(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "</span>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 4516), Tuple.Create("\"", 4576)
, Tuple.Create(Tuple.Create("", 4524), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 4524), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 4778), Tuple.Create("\"", 4827)
, Tuple.Create(Tuple.Create("", 4786), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 4786), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(RepliedToYourCommentNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideByIdNotSafe(notification.Comment.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__replied-to-your-comment-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                        WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "#comment-");

                                                                                                 WriteTo(__razor_helper_writer, notification.Comment.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, " ответил");

                                 WriteTo(__razor_helper_writer,  notification.Comment.Author.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " на&nbsp;ваш комментарий\r\n\t\t\t\t<span");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 5580), Tuple.Create("\"", 5646)
, Tuple.Create(Tuple.Create("", 5588), Tuple.Create<System.Object, System.Int32>(notification.ParentComment.Text.TruncateWithEllipsis(200)
, 5588), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__cite\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                             WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.ParentComment.Text, 50, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</span>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 5821), Tuple.Create("\"", 5881)
, Tuple.Create(Tuple.Create("", 5829), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 5829), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\tк&nbsp;слайду ");

WriteTo(__razor_helper_writer, SlideLink(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t<span");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 6145), Tuple.Create("\"", 6194)
, Tuple.Create(Tuple.Create("", 6153), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 6153), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                          WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</span>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(LikedYourCommentNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideByIdNotSafe(notification.Comment.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__liked-your-comment-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                   WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "#comment-");

                                                                                            WriteTo(__razor_helper_writer, notification.Comment.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.LikedUser));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.LikedUser));

WriteLiteralTo(__razor_helper_writer, " лайкнул");

                                                                         WriteTo(__razor_helper_writer,  notification.LikedUser.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " ваш комментарий</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 6925), Tuple.Create("\"", 6985)
, Tuple.Create(Tuple.Create("", 6933), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 6933), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 7187), Tuple.Create("\"", 7236)
, Tuple.Create(Tuple.Create("", 7195), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 7195), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(PassedManualExerciseCheckingNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = (ExerciseSlide)course.GetSlideByIdNotSafe(notification.Checking.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__passed-manual-execise-checking-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                               WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " ");

                       WriteTo(__razor_helper_writer,  notification.IsRecheck ? "пере" : "");

WriteLiteralTo(__razor_helper_writer, "проверил");

                                                                       WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " ваше решение<br/>по&nbsp;«");

                                                                                                                                                   WriteTo(__razor_helper_writer, slide.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»\r\n\t\t\t</div>\r\n");

			
              
				var score = SlideCheckingsRepo.ConvertExerciseManualCheckingPercentToScore(notification.Checking.Percent.Value, slide.Scoring.ScoreWithCodeReview).PluralizeInRussian(RussianPluralizationOptions.Score);
			
WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__score\"");

WriteLiteralTo(__razor_helper_writer, ">Вы получили ");

                                          WriteTo(__razor_helper_writer, score);

WriteLiteralTo(__razor_helper_writer, " из ");

                                                    WriteTo(__razor_helper_writer, slide.Scoring.ScoreWithCodeReview.PluralizeInRussian(RussianPluralizationOptions.Score));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 8496), Tuple.Create("\"", 8545)
, Tuple.Create(Tuple.Create("", 8504), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 8504), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(PassedManualQuizCheckingNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = (QuizSlide)course.GetSlideByIdNotSafe(notification.Checking.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__passed-manual-quiz-checking-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                            WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " проверил");

                               WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " ваш тест<br/>«");

                                                                                               WriteTo(__razor_helper_writer, slide.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__score\"");

WriteLiteralTo(__razor_helper_writer, ">Вы получили ");

                                          WriteTo(__razor_helper_writer, notification.Checking.Score);

WriteLiteralTo(__razor_helper_writer, " из ");

                                                                          WriteTo(__razor_helper_writer, slide.MaxScore.PluralizeInRussian(RussianPluralizationOptions.ScoreDative));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 9531), Tuple.Create("\"", 9580)
, Tuple.Create(Tuple.Create("", 9539), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 9539), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(ReceivedCertificateNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__received-certificate-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                     WriteTo(__razor_helper_writer, Url.RouteUrl("Certificate", new { certificateId = notification.CertificateId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">Поздравляем! Вы получили сертификат по&nbsp;курсу «");

                                                                                  WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 10272), Tuple.Create("\"", 10321)
, Tuple.Create(Tuple.Create("", 10280), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 10280), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(ReceivedAdditionalScoreNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var unit = course.GetUnitByIdNotSafe(notification.Score.UnitId);
	var scoringGroup = unit.Scoring.Groups[notification.Score.ScoringGroupId];

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__received-additional-score-notification without-link media\"" +
"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " поставил");

                               WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " вам баллы <b>");

                                                                                              WriteTo(__razor_helper_writer, scoringGroup.Name);

WriteLiteralTo(__razor_helper_writer, "</b> в&nbsp;модуле «");

                                                                                                                                    WriteTo(__razor_helper_writer, unit.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__score\"");

WriteLiteralTo(__razor_helper_writer, ">Вы получили ");

                                          WriteTo(__razor_helper_writer, notification.Score.Score);

WriteLiteralTo(__razor_helper_writer, " из ");

                                                                       WriteTo(__razor_helper_writer, scoringGroup.MaxAdditionalScore.PluralizeInRussian(RussianPluralizationOptions.ScoreDative));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 11382), Tuple.Create("\"", 11431)
, Tuple.Create(Tuple.Create("", 11390), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 11390), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(ReceivedCommentToCodeReviewNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideByIdNotSafe(notification.Comment.Review.ExerciseChecking.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__received-comment-to-code-review-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                                WriteTo(__razor_helper_writer, notification.GetUrl(course, "", User.Identity.GetUserId()));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " прокомментировал");

                                       WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " код-ревью задания «");

                                                                                                            WriteTo(__razor_helper_writer, slide.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 12254), Tuple.Create("\"", 12314)
, Tuple.Create(Tuple.Create("", 12262), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 12262), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 12516), Tuple.Create("\"", 12565)
, Tuple.Create(Tuple.Create("", 12524), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 12524), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(JoinedToYourGroupNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__joined-to-your-group-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                     WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.JoinedUser));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.JoinedUser));

WriteLiteralTo(__razor_helper_writer, " присоедини");

                                WriteTo(__razor_helper_writer,  notification.JoinedUser.Gender.ChooseEnding("лся", "лась"));

WriteLiteralTo(__razor_helper_writer, " к&nbsp;вашей группе <b>«");

                                                                                                                      WriteTo(__razor_helper_writer, notification.Group.Name);

WriteLiteralTo(__razor_helper_writer, "»</b>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 13334), Tuple.Create("\"", 13383)
, Tuple.Create(Tuple.Create("", 13342), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 13342), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(GrantedAccessToGroupNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__granted-access-to-group-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                        WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Access.User));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.Access.GrantedBy));

WriteLiteralTo(__razor_helper_writer, " назначил");

                                    WriteTo(__razor_helper_writer,  notification.Access.GrantedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " вас преподавателем группы <b>«");

                                                                                                                         WriteTo(__razor_helper_writer, notification.Access.Group.Name.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</b> в&nbsp;курсе «");

                                                                                                                                                                                               WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "».\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 14237), Tuple.Create("\"", 14286)
, Tuple.Create(Tuple.Create("", 14245), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 14245), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(RevokedAccessToGroupNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__revoked-access-to-group-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                        WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Access.User));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\tВы перестали быть преподавателем группы <b>«");

                              WriteTo(__razor_helper_writer, notification.Access.Group.Name.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</b> в курсе «");

                                                                                               WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "».\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 15044), Tuple.Create("\"", 15093)
, Tuple.Create(Tuple.Create("", 15052), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 15052), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(GroupMembersHaveBeenRemovedNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__group-members-have-been-removed-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                                WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " удалил");

                             WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " ");

                                                                               WriteTo(__razor_helper_writer, notification.UsersCount.PluralizeInRussian(RussianPluralizationOptions.StudentsDative));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\tиз группы&nbsp;<b>«");

     WriteTo(__razor_helper_writer, notification.Group.Name.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</b> в&nbsp;курсе «");

                                                                    WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»: ");

                                                                                                       WriteTo(__razor_helper_writer, notification.UserDescriptions);

WriteLiteralTo(__razor_helper_writer, ".\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 16057), Tuple.Create("\"", 16106)
, Tuple.Create(Tuple.Create("", 16065), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 16065), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(GroupMembersHaveBeenAddedNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__group-members-have-been-added-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                              WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " добавил");

                              WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " ");

                                                                                WriteTo(__razor_helper_writer, notification.UsersCount.PluralizeInRussian(RussianPluralizationOptions.StudentsDative));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\tв группу&nbsp;<b>«");

    WriteTo(__razor_helper_writer, notification.Group.Name.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</b> в&nbsp;курсе «");

                                                                   WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»: ");

                                                                                                      WriteTo(__razor_helper_writer, notification.UserDescriptions);

WriteLiteralTo(__razor_helper_writer, ".\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 17066), Tuple.Create("\"", 17115)
, Tuple.Create(Tuple.Create("", 17074), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 17074), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(NewCommentForInstructorsOnlyNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideByIdNotSafe(notification.Comment.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__new-comment-for-instructors-only-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                                 WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "#comment-");

                                                                                                          WriteTo(__razor_helper_writer, notification.Comment.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__subheader\"");

WriteLiteralTo(__razor_helper_writer, ">к&nbsp;слайду ");

                                                     WriteTo(__razor_helper_writer, SlideLink(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "</span>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"comments-for-instructors-only__description\"");

WriteLiteralTo(__razor_helper_writer, ">Комментарий для преподавателей:</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 18017), Tuple.Create("\"", 18077)
, Tuple.Create(Tuple.Create("", 18025), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 18025), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 18279), Tuple.Create("\"", 18328)
, Tuple.Create(Tuple.Create("", 18287), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 18287), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(AddedInstructorNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__added-instructor-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                 WriteTo(__razor_helper_writer, Url.Action("Users", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.AddedUser));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.AddedUser));

WriteLiteralTo(__razor_helper_writer, " стал");

                                                                      WriteTo(__razor_helper_writer,  notification.AddedUser.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " преподавателем курса «");

                                                                                                                                            WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 19059), Tuple.Create("\"", 19108)
, Tuple.Create(Tuple.Create("", 19067), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 19067), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(CreatedGroupNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__created-group-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                              WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " создал");

                                                                          WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " группу «");

                                                                                                                                    WriteTo(__razor_helper_writer, notification.Group.Name.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "» в&nbsp;курсе «");

                                                                                                                                                                                               WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 19887), Tuple.Create("\"", 19936)
, Tuple.Create(Tuple.Create("", 19895), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 19895), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(UploadedPackageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__uploaded-package-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                 WriteTo(__razor_helper_writer, Url.Action("Packages", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " загрузил");

                                                                            WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " новую версию курса «");

                                                                                                                                                  WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 20678), Tuple.Create("\"", 20727)
, Tuple.Create(Tuple.Create("", 20686), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 20686), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(NotUploadedPackageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notuploaded-package-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                    WriteTo(__razor_helper_writer, GitUtils.RepoUrlToCommitLink(notification.RepoUrl, notification.CommitHash));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">Ошибка загрузки новой версии курса «");

                                                                   WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "». Коммит ");

                                                                                                             WriteTo(__razor_helper_writer, notification.CommitHash.Substring(0, 8));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 21447), Tuple.Create("\"", 21496)
, Tuple.Create(Tuple.Create("", 21455), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 21455), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(PublishedPackageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__published-package-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                  WriteTo(__razor_helper_writer, Url.Action("Packages", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " опубликовал");

                                                                               WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " новую версию курса «");

                                                                                                                                                     WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 22243), Tuple.Create("\"", 22292)
, Tuple.Create(Tuple.Create("", 22251), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 22251), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(CourseExportedToStepikNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__course-exported-to-stepik-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                          WriteTo(__razor_helper_writer, Url.Action("Process", "Stepik", new { courseId = course.Id, processId = notification.ProcessId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

			
             if (notification.Process.IsSuccess)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">Курс <b>«");

                                            WriteTo(__razor_helper_writer, course.Title.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</b> успешно экспортирован на&nbsp;Степик. Нажмите для&nbsp;подробностей.</div>\r" +
"\n");

			}
			else
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">Произошла ошибка при копировании курса <b>«");

                                                                              WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "»</b> на&nbsp;Степик. Нажмите для&nbsp;подробностей.</div>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 23285), Tuple.Create("\"", 23334)
, Tuple.Create(Tuple.Create("", 23293), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 23293), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(GroupIsArchivedNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__group-is-archived-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                  WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">Ваша группа <b>«");

                                               WriteTo(__razor_helper_writer, notification.Group.Name.MakeNestedQuotes());

WriteLiteralTo(__razor_helper_writer, "»</b> архивирована. Чтобы восстановить, используйте вкладку Архивные на странице " +
"групп.</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 24073), Tuple.Create("\"", 24122)
, Tuple.Create(Tuple.Create("", 24081), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 24081), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
